# Generated by Django 4.2.2 on 2023-06-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_convidado_compromisso_pessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compromisso',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='compromisso',
            name='convidados',
            field=models.ManyToManyField(to='agenda.convidado'),
        ),
    ]
